using System.Collections.Generic;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using Noggog;
using System.IO;
using ArmorDistributor.Utils;
using log4net.Config;
using log4net;
using System.Reflection;
using static ArmorDistributor.Config.Settings;
using ArmorDistributor.Managers;
using System;
using ArmorDistributor.NPC;
using Mutagen.Bethesda.Plugins;
using ArmorDistributor.Config;
using Mutagen.Bethesda.Environments;
using Mutagen.Bethesda.Plugins.Cache;
using System.Text.RegularExpressions;
using Mutagen.Bethesda.FormKeys.SkyrimSE;

namespace ArmorDistributor
{
    class Program
    {
        private static readonly ILog Logger = LogManager.GetLogger(typeof(Program));
        internal static IGameEnvironmentState<ISkyrimMod, ISkyrimModGetter> PatcherEnv = GameEnvironment.Typical.Skyrim(
                SkyrimRelease.SkyrimSE, LinkCachePreferences.Default);

        internal static Settings? Settings = null;
        static Lazy<Settings> LazySettings = null!;            

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .SetAutogeneratedSettings(nickname: "Settings",
                    path: "settings.json", out LazySettings, true)
                .SetTypicalOpen(GameRelease.SkyrimSE, "ADP - Delete Me.esp")
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPacher)
                .Run(args);
        }

        private static void RunPacher(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Settings = LazySettings.Value;
            Settings.Init(state);
            PatcherEnv.Dispose();
            Console.WriteLine("\nSettings loaded...");

            //HelperUtils.mergePlugins(@"E:\Modded\SSE-Aldrnari142\mods\Armor Merged\merge - Armor Merged\merge.json", false);
            ////return;

            //List<string> esps = new();
            //esps.Add(@"E:\Modded\SSE-Aldrnari142\mods\Deze Armor and Clothing SPIDified\SPIDeze_DISTR.ini");
            //esps.Add(@"E:\Modded\SSE-Aldrnari142\mods\SPID Bikinification\Arial Dress Up Bikini Bandits Vanilla - SPID_DISTR.ini");
            //esps.Add(@"E:\Modded\SSE-Aldrnari142\mods\Distributed Divine Elegance with SPID featuring Fancy Erikur and Nazeem\Arial Distributed Divine Elegance - SPID_DISTR.ini");
            //HelperUtils.updateSPIDFile(@"E:\Modded\SSE-Aldrnari142\mods\Armor Merged\merge - Armor Merged\map.json", esps, "Armor Merged.esp");
            //return;

            if (!RequirementsFullfilled(state)) return;

            var patchName = Settings.PatcherSettings.PatcherPrefix + "Patch 1.esp";
            var patch = FileUtils.GetOrAddPatch(patchName);
            patch = new OutfitManager(state).Process(patch);

            //// Little house keeping 
            //if (Settings.UserSettings.CreateBashPatch)
            //{
            //    CreateBashPatchForLVLI(state, patch);
            //    CreateBashPatchForLVLN(state, patch);                
            //}

            ////Saving all the patches to disk
            //Console.WriteLine("\nSaving all the patches to disk...");
            //Settings.Patches.ForEach(p => FileUtils.SaveMod(state, p));
            Console.WriteLine("Patching completed, Enjoy your game...\n\n");
        }

        private static void CreateBashPatchForLVLI(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, ISkyrimMod patch)
        {
            Console.WriteLine("\nCreating Leveled List bash patch...");
            patch = FileUtils.GetIncrementedMod(patch);
            foreach (ILeveledItemGetter lvli in state.LoadOrder.PriorityOrder
                .WinningOverrides<ILeveledItemGetter>()
                .Where(x => !Program.Settings.UserSettings.ModsToSkip.Contains(x.FormKey.ModKey)))
            {
                List<ILeveledItemGetter> lvlis = state.LinkCache.ResolveAll<ILeveledItemGetter>(lvli.FormKey).ToList();
                if (lvlis.Count > 1)
                {
                    List<LeveledItemEntry> entries = new();
                    lvlis.ForEach(x => entries.AddRange(x.Entries.EmptyIfNull().Select(entry => entry.DeepCopy())));
                    LeveledItem lvl = patch.LeveledItems.GetOrAddAsOverride(lvlis.First());
                    lvl.Entries = new ExtendedList<LeveledItemEntry>();
                    OutfitUtils.AddEntriesToLeveledList(patch, lvl, entries);
                }
            }
        }

        private static void CreateBashPatchForLVLN(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, ISkyrimMod patch)
        {
            Console.WriteLine("Creating Leveled NPC bash patch...");
            patch = FileUtils.GetIncrementedMod(patch);
            foreach (ILeveledNpcGetter lvli in state.LoadOrder.PriorityOrder.WinningOverrides<ILeveledNpcGetter>()
                .Where(x => !Program.Settings.UserSettings.ModsToSkip.Contains(x.FormKey.ModKey)))
            {
                List<ILeveledNpcGetter> lvlis = Settings.Cache.ResolveAll<ILeveledNpcGetter>(lvli.FormKey).ToList();
                if (lvlis.Count > 1)
                {
                    List<LeveledNpcEntry> entries = new();
                    lvlis.ForEach(x => entries.AddRange(x.Entries.EmptyIfNull().Select(entry => entry.DeepCopy())));
                    LeveledNpc lvl = patch.LeveledNpcs.GetOrAddAsOverride(lvlis.First());
                    lvl.Entries = new ();
                    OutfitUtils.AddEntriesToLeveledList(patch, lvl, entries);
                }
            }
        }

        private static bool RequirementsFullfilled(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Console.WriteLine("Validating requirements...");
            string spidLoc = Path.Combine(state.DataFolderPath, "skse", "plugins", "po3_SpellPerkItemDistributor.dll");
            if (!File.Exists(spidLoc))
            {
                Logger.ErrorFormat("Spell Perk Item Distributer mod is not found. Install it properly and re-run the patcher...");
                return false;
            }

            // Checking patched mods are enabled in load order
            bool patchExists = false;
            foreach (var modKey in state.LoadOrder.PriorityOrder
                .Select(x => x.ModKey))
            {
                if (modKey.FileName.String.StartsWith(Settings.PatcherSettings.PatcherPrefix))
                {
                    Logger.ErrorFormat("Disable or delete mod to continue: " + modKey.FileName);
                    patchExists = true;
                }
            }

            // Checking for JSOn File Categories
            var categories = Settings.PatcherSettings.OutfitRegex.Keys;
            Settings.UserSettings.ArmorMods.ForEach(s => {
                s.Value.ForEach(x => {
                    if (x!="Generic" && !categories.Contains(x))
                        Logger.WarnFormat("{0} contains invalid Category:{1}", s.Key, x);
                });
            });

            //// Copying the scripts
            //var src = Path.Combine(state.ExtraSettingsDataPath, "Scripts");
            //var des = Path.Combine(state.DataFolderPath, "Scripts");
            //FileUtils.CopyDirectory(src, des);

            Console.WriteLine("All the requirements are validated...");
            return !patchExists;
        }
        
        static Program() {
            // Init logger
            var logRepository = LogManager.GetRepository(Assembly.GetEntryAssembly());
            XmlConfigurator.Configure(logRepository, new FileInfo("log4net.config"));
        }
    }
}
