using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArmorDistributor.Config
{
    public enum TCategory
    {
        Generic = 0,
        Archer = 1,
        Assassin = 2,
        Bandit = 3,
        BarKeeper = 4,
        Blacksmith = 5,
        Blades = 6,
        Child = 7,
        Citizen = 8,
        Companions = 9,
        Dawnguard = 10,
        Falmer = 11,
        Farmer = 12,
        Forsworn = 13,
        Greybeard = 14,
        GuardsEastmarch = 15,
        GuardsFalkreath = 16,
        GuardsHaafingar = 17,
        GuardsHjaalmarch = 18,
        GuardsImperial = 19,
        GuardsPale = 20,
        GuardsReach = 21,
        GuardsRift = 22,
        GuardsStormcloak = 23,
        GuardsWhiterun = 24,
        GuardsWindhelm = 25,
        GuardsWinterhold = 26,
        Housecarl = 27,
        Hunter = 28,
        Jarl = 29,
        Knight = 30,
        Mage = 31,
        MaterialBonemold = 32,
        MaterialChitin = 33,
        MaterialDragonbone = 34,
        MaterialDragonplate = 35,
        MaterialDragonscale = 36,
        MaterialDwarven = 37,
        MaterialEbony = 38,
        MaterialElven = 39,
        MaterialGlass = 40,
        MaterialHide = 41,
        MaterialIron = 42,
        MaterialLeather = 43,
        MaterialLeatherNetch = 44,
        MaterialNordic = 45,
        MaterialScaled = 46,
        MaterialStalhrim = 47,
        MaterialSteel = 48,
        MaterialSteelPlate = 49,
        MaterialStudded = 50,
        Merchant = 51,
        Miner = 52,
        Nightingale = 53,
        Penitus = 54,
        Poor = 55,
        Prisoner = 56,
        RaceAltmer = 57,
        RaceArgonian = 58,
        RaceBosmer = 59,
        RaceBreton = 60,
        RaceDaedra = 61,
        RaceDunmer = 62,
        RaceFalmer = 63,
        RaceImperial = 64,
        RaceKhajiit = 65,
        RaceNord = 66,
        RaceOrc = 67,
        RaceRedguard = 68,
        RaceVampire = 69,
        Sailor = 70,
        Skaal = 71,
        SleepOutfit = 72,
        Stormcloak = 73,
        Thalmor = 74,
        Thief = 75,
        Traveller = 76,
        Vigilant = 77,
        Warrior = 78,
        WeddingDress = 79
    }
}
