using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArmorDistributor.Config
{
    public enum TCategory
    {
        Generic = 0,
        Archer = 1,
        Assassin = 2,
        BandedArmor = 3,
        Bandit = 4,
        BarKeeper = 5,
        Blacksmith = 6,
        Blades = 7,
        BonemoldArmor = 8,
        Child = 9,
        ChitinArmor = 10,
        Citizen = 11,
        CollegeWizard = 12,
        Companions = 13,
        CourtWizard = 14,
        Daedra = 15,
        DarkBrotherhood = 16,
        Dawnguard = 17,
        DragonplateArmor = 18,
        DragonscaleArmor = 19,
        DwarvenArmor = 20,
        EastmarchGuards = 21,
        EbonyArmor = 22,
        ElvenArmor = 23,
        FalkreathGuards = 24,
        Farmer = 25,
        Forsworn = 26,
        GlassArmor = 27,
        HaafingarGuards = 28,
        HideArmor = 29,
        HjaalmarchGuards = 30,
        Hunter = 31,
        Imperial = 32,
        ImperialGuards = 33,
        IronArmor = 34,
        Jarl = 35,
        Knight = 36,
        LeatherArmor = 37,
        Mage = 38,
        Mercenary = 39,
        Merchant = 40,
        Miner = 41,
        Necromancer = 42,
        NetchLeatherArmor = 43,
        Nightingale = 44,
        NordicArmor = 45,
        OrcishArmor = 46,
        Orcs = 47,
        PaleGuards = 48,
        Poor = 49,
        Prisoner = 50,
        ReachGuards = 51,
        Redguard = 52,
        RiftGuards = 53,
        Sailor = 54,
        ScaledArmor = 55,
        Servent = 56,
        Skaal = 57,
        StalhrimArmor = 58,
        SteelArmor = 59,
        Stormcloak = 60,
        StormcloakGuards = 61,
        StuddedArmor = 62,
        Thalmor = 63,
        Thief = 64,
        Vampires = 65,
        Vigilant = 66,
        Warrior = 67,
        WeddingDress = 68,
        WenchTavern = 69,
        WhiterunGuards = 70,
        WindhelmGuards = 71,
        WinterholdGuards = 72
    }
}
